### PR TITLE
Bump changelog for 4.0.1 release

### PR DESCRIPTION
**Pull request by jtilly**
Checklist
* [x] Added a `CHANGELOG.rst` entry

We need a tabmat release to stay compatible with the latest scipy release (see https://github.com/Quantco/glum/issues/811).

### CODE REVIEW

**Review by lbittarello — APPROVED** [review]

**Comment by jtilly** [comment]
macOS builds are [failing](https://github.com/Quantco/tabmat/actions/runs/9657523540/job/26636945871?pr=372#step:5:348) with

```
+ delocate-wheel --require-archs x86_64 -w /private/var/folders/4z/th_0342d7sv9wl7kb3yfllq80000gn/T/cibw-run-gnl3b8cv/cp39-macosx_x86_64/repaired_wheel -v /private/var/folders/4z/th_0342d7sv9wl7kb3yfllq80000gn/T/cibw-run-gnl3b8cv/cp39-macosx_x86_64/built_wheel/tabmat-0.0.post1+g1cdc18a-cp39-cp39-macosx_10_13_x86_64.whl
  INFO:delocate.delocating:Copying library /usr/local/miniconda/envs/build/lib/libomp.dylib to tabmat/.dylibs/libomp.dylib
  INFO:delocate.delocating:Copying library /usr/local/miniconda/envs/build/lib/libc++.1.0.dylib to tabmat/.dylibs/libc++.1.0.dylib
  INFO:delocate.delocating:Copying library /usr/local/miniconda/envs/build/lib/libjemalloclocal.2.dylib to tabmat/.dylibs/libjemalloclocal.2.dylib
  INFO:delocate.delocating:Modifying install name in tabmat/ext/categorical.cpython-39-darwin.so from @rpath/libomp.dylib to @loader_path/../.dylibs/libomp.dylib
  INFO:delocate.delocating:Modifying install name in tabmat/ext/split.cpython-39-darwin.so from @rpath/libomp.dylib to @loader_path/../.dylibs/libomp.dylib
  INFO:delocate.delocating:Modifying install name in tabmat/ext/sparse.cpython-39-darwin.so from @rpath/libomp.dylib to @loader_path/../.dylibs/libomp.dylib
  INFO:delocate.delocating:Modifying install name in tabmat/ext/dense.cpython-39-darwin.so from @rpath/libomp.dylib to @loader_path/../.dylibs/libomp.dylib
  INFO:delocate.delocating:Modifying install name in tabmat/ext/sparse.cpython-39-darwin.so from @rpath/libjemalloclocal.2.dylib to @loader_path/../.dylibs/libjemalloclocal.2.dylib
  INFO:delocate.delocating:Modifying install name in tabmat/ext/dense.cpython-39-darwin.so from @rpath/libjemalloclocal.2.dylib to @loader_path/../.dylibs/libjemalloclocal.2.dylib
  INFO:delocate.delocating:Modifying install name in tabmat/ext/categorical.cpython-39-darwin.so from @rpath/libc++.1.dylib to @loader_path/../.dylibs/libc++.1.0.dylib
  INFO:delocate.delocating:Modifying install name in tabmat/ext/split.cpython-39-darwin.so from @rpath/libc++.1.dylib to @loader_path/../.dylibs/libc++.1.0.dylib
  INFO:delocate.delocating:Modifying install name in tabmat/ext/sparse.cpython-39-darwin.so from @rpath/libc++.1.dylib to @loader_path/../.dylibs/libc++.1.0.dylib
  INFO:delocate.delocating:Modifying install name in tabmat/ext/dense.cpython-39-darwin.so from @rpath/libc++.1.dylib to @loader_path/../.dylibs/libc++.1.0.dylib
  Fixing: /private/var/folders/4z/th_0342d7sv9wl7kb3yfllq80000gn/T/cibw-run-gnl3b8cv/cp39-macosx_x86_64/built_wheel/tabmat-0.0.post1+g1cdc18a-cp39-cp39-macosx_10_13_x86_64.whl
  Traceback (most recent call last):
    File "/private/var/folders/4z/th_0342d7sv9wl7kb3yfllq80000gn/T/cibw-run-gnl3b8cv/cp39-macosx_x86_64/build/venv/bin/delocate-wheel", line 8, in <module>
      sys.exit(main())
    File "/private/var/folders/4z/th_0342d7sv9wl7kb3yfllq80000gn/T/cibw-run-gnl3b8cv/cp39-macosx_x86_64/build/venv/lib/python3.9/site-packages/delocate/cmd/delocate_wheel.py", line 110, in main
      copied = delocate_wheel(
    File "/private/var/folders/4z/th_0342d7sv9wl7kb3yfllq80000gn/T/cibw-run-gnl3b8cv/cp39-macosx_x86_64/build/venv/lib/python3.9/site-packages/delocate/delocating.py", line 1004, in delocate_wheel
      out_wheel_fixed = _check_and_update_wheel_name(
    File "/private/var/folders/4z/th_0342d7sv9wl7kb3yfllq80000gn/T/cibw-run-gnl3b8cv/cp39-macosx_x86_64/build/venv/lib/python3.9/site-packages/delocate/delocating.py", line 839, in _check_and_update_wheel_name
      raise DelocationError(
  delocate.libsana.DelocationError: Library dependencies do not satisfy target MacOS version 10.13:
  /private/var/folders/4z/th_0342d7sv9wl7kb3yfllq80000gn/T/tmp7sfy2sf_/wheel/tabmat/.dylibs/libc++.1.0.dylib has a minimum target of 12.0
```

@xhochy can I bump https://github.com/Quantco/tabmat/blob/09149c96d7f4a476d836c567e3884fa51c22d615/pyproject.toml#L62 to 12?

**Comment by ForrestQuant** [comment]
> macOS builds are [failing](https://github.com/Quantco/tabmat/actions/runs/9657523540/job/26636945871?pr=372#step:5:348) with
> 
> ```
> + delocate-wheel --require-archs x86_64 -w /private/var/folders/4z/th_0342d7sv9wl7kb3yfllq80000gn/T/cibw-run-gnl3b8cv/cp39-macosx_x86_64/repaired_wheel -v /private/var/folders/4z/th_0342d7sv9wl7kb3yfllq80000gn/T/cibw-run-gnl3b8cv/cp39-macosx_x86_64/built_wheel/tabmat-0.0.post1+g1cdc18a-cp39-cp39-macosx_10_13_x86_64.whl
>   INFO:delocate.delocating:Copying library /usr/local/miniconda/envs/build/lib/libomp.dylib to tabmat/.dylibs/libomp.dylib
>   INFO:delocate.delocating:Copying library /usr/local/miniconda/envs/build/lib/libc++.1.0.dylib to tabmat/.dylibs/libc++.1.0.dylib
>   INFO:delocate.delocating:Copying library /usr/local/miniconda/envs/build/lib/libjemalloclocal.2.dylib to tabmat/.dylibs/libjemalloclocal.2.dylib
>   INFO:delocate.delocating:Modifying install name in tabmat/ext/categorical.cpython-39-darwin.so from @rpath/libomp.dylib to @loader_path/../.dylibs/libomp.dylib
>   INFO:delocate.delocating:Modifying install name in tabmat/ext/split.cpython-39-darwin.so from @rpath/libomp.dylib to @loader_path/../.dylibs/libomp.dylib
>   INFO:delocate.delocating:Modifying install name in tabmat/ext/sparse.cpython-39-darwin.so from @rpath/libomp.dylib to @loader_path/../.dylibs/libomp.dylib
>   INFO:delocate.delocating:Modifying install name in tabmat/ext/dense.cpython-39-darwin.so from @rpath/libomp.dylib to @loader_path/../.dylibs/libomp.dylib
>   INFO:delocate.delocating:Modifying install name in tabmat/ext/sparse.cpython-39-darwin.so from @rpath/libjemalloclocal.2.dylib to @loader_path/../.dylibs/libjemalloclocal.2.dylib
>   INFO:delocate.delocating:Modifying install name in tabmat/ext/dense.cpython-39-darwin.so from @rpath/libjemalloclocal.2.dylib to @loader_path/../.dylibs/libjemalloclocal.2.dylib
>   INFO:delocate.delocating:Modifying install name in tabmat/ext/categorical.cpython-39-darwin.so from @rpath/libc++.1.dylib to @loader_path/../.dylibs/libc++.1.0.dylib
>   INFO:delocate.delocating:Modifying install name in tabmat/ext/split.cpython-39-darwin.so from @rpath/libc++.1.dylib to @loader_path/../.dylibs/libc++.1.0.dylib
>   INFO:delocate.delocating:Modifying install name in tabmat/ext/sparse.cpython-39-darwin.so from @rpath/libc++.1.dylib to @loader_path/../.dylibs/libc++.1.0.dylib
>   INFO:delocate.delocating:Modifying install name in tabmat/ext/dense.cpython-39-darwin.so from @rpath/libc++.1.dylib to @loader_path/../.dylibs/libc++.1.0.dylib
>   Fixing: /private/var/folders/4z/th_0342d7sv9wl7kb3yfllq80000gn/T/cibw-run-gnl3b8cv/cp39-macosx_x86_64/built_wheel/tabmat-0.0.post1+g1cdc18a-cp39-cp39-macosx_10_13_x86_64.whl
>   Traceback (most recent call last):
>     File "/private/var/folders/4z/th_0342d7sv9wl7kb3yfllq80000gn/T/cibw-run-gnl3b8cv/cp39-macosx_x86_64/build/venv/bin/delocate-wheel", line 8, in <module>
>       sys.exit(main())
>     File "/private/var/folders/4z/th_0342d7sv9wl7kb3yfllq80000gn/T/cibw-run-gnl3b8cv/cp39-macosx_x86_64/build/venv/lib/python3.9/site-packages/delocate/cmd/delocate_wheel.py", line 110, in main
>       copied = delocate_wheel(
>     File "/private/var/folders/4z/th_0342d7sv9wl7kb3yfllq80000gn/T/cibw-run-gnl3b8cv/cp39-macosx_x86_64/build/venv/lib/python3.9/site-packages/delocate/delocating.py", line 1004, in delocate_wheel
>       out_wheel_fixed = _check_and_update_wheel_name(
>     File "/private/var/folders/4z/th_0342d7sv9wl7kb3yfllq80000gn/T/cibw-run-gnl3b8cv/cp39-macosx_x86_64/build/venv/lib/python3.9/site-packages/delocate/delocating.py", line 839, in _check_and_update_wheel_name
>       raise DelocationError(
>   delocate.libsana.DelocationError: Library dependencies do not satisfy target MacOS version 10.13:
>   /private/var/folders/4z/th_0342d7sv9wl7kb3yfllq80000gn/T/tmp7sfy2sf_/wheel/tabmat/.dylibs/libc++.1.0.dylib has a minimum target of 12.0
> ```
> 
> @xhochy can I bump
> 
> https://github.com/Quantco/tabmat/blob/09149c96d7f4a476d836c567e3884fa51c22d615/pyproject.toml#L62
> 
> to 12?

11 should work (equally) fine and leave less people behind.

**Comment by jtilly** [comment]
Apparently, this needs to be 12. 

See https://github.com/Quantco/tabmat/actions/runs/9657842805/job/26637855297?pr=372#step:5:348:

>   delocate.libsana.DelocationError: Library dependencies do not satisfy target MacOS version 11.0:
  /private/var/folders/84/dbvvycbn3pl4z4wxpcykqzt40000gn/T/tmpkuko50yh/wheel/tabmat/.dylibs/libc++.1.0.dylib has a minimum target of 12.0

**Comment by xhochy** [comment]
You could probably fix it by adjusting the compiler flags, but I don't think this is worth the effort.

**Pull request merged**
